//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swift_Queue_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int Id { get; set; }
        public int customer_fid { get; set; }
        public int Queue_no { get; set; }
        public int Status { get; set; }
        public int Party_size { get; set; }
        public int Queue_fid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Queue_Setting Queue_Setting { get; set; }
    }
}
